# Generated by Django 5.2.5 on 2025-08-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_rename_days_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="food",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
