# Generated by Django 5.2.5 on 2025-08-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0003_alter_day_id_alter_food_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="date",
            field=models.DateField(verbose_name="date"),
        ),
        migrations.AlterField(
            model_name="food",
            name="days",
            field=models.ManyToManyField(blank=True, to="food.day"),
        ),
    ]
