# Generated by Django 5.2.5 on 2025-08-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0004_alter_day_date_alter_food_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="color",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
